---
name: Manage Alpa Package
description: React on requests to create/delete package to/from Alpa repository.

branding:
  icon: upload
  color: blue

inputs:
  gh-api-token:
    description: GitHub token of your bot with read/write access
    required: true
  copr-login:
    description: login from https://copr.fedorainfracloud.org/api/
    required: true
  copr-token:
    description: token from https://copr.fedorainfracloud.org/api/
    required: true
  debug:
    description: Turn on to see debug logs
    required: false
    default: "false"

runs:
  using: docker
  image: "Dockerfile"
